### PR TITLE
using steal.clone() to dependency inject a Tournament Model for testing

### PR DESCRIPTION
**Pull request by phillipskevin**

### CODE REVIEW

**Comment by justinbmeyer** [comment]
@phillipskevin Think you could redo this test with the results of https://github.com/stealjs/steal/issues/509?

**Comment by phillipskevin** [comment]
@justinbmeyer Yeah, I'll plan to redo this once that is working.

**Comment by phillipskevin** [comment]
@justinbmeyer this is updated to use steal 0.15.0 and steal-clone. It looks like a test is failing, but it's not the test using steal-clone.

**Comment by akagomez** [comment]
I'm going to re-submit this PR into `staging`. Currently it's setup to go to `master`.

**Pull request closed without merging**
